"""Offline fixture transport — simulates a local LLM response layer.

This module produces a structured dict that mimics what a real
Ollama / LM Studio / llama.cpp call would return, without ever
touching the network or a running model process.

It is NOT a provider — it is a transport-layer simulation that
future real providers (local-http, openai) would reuse.

Behavior:
- Fully offline
- No network access
- No environment variable reads
- Generates 8 structured cards from the prompt pack
- Uses only existing chunk IDs
- Never invents specific numbers or external facts
"""

from __future__ import annotations

from typing import List

from explainlens.providers.prompt_contract import ProviderPromptPack

# ── Constants ─────────────────────────────────────────────────────

_CARD_TITLES = [
    "What's This About?",
    "The Core Problem",
    "Key Insight",
    "How It Works",
    "Evidence Check",
    "Why It Matters",
    "Limits & Caveats",
    "What This Means for You",
]

_VISUAL_METAPHORS = [
    "A magnifying glass revealing hidden text on a page",
    "A maze with one illuminated path leading to a question mark",
    "A detective's corkboard with pins and strings connecting clues",
    "A blueprint unrolling across a drafting table",
    "A scale balancing evidence on two sides",
    "A lighthouse beam cutting through fog",
    "A caution sign at the edge of a bridge",
    "A compass pointing to a door labeled 'Next Steps'",
]

_VISUAL_SCENES = [
    "Close-up of an open book with glowing annotations floating above it. "
    "A reader's hand traces a line of text.",
    "Overhead view of a complex maze. One path glows faintly. "
    "At the center sits a luminous question mark.",
    "Wooden detective board with photographs, red string, and sticky notes. "
    "A magnifying glass hovers over the central clue.",
    "Blueprint table with a half-unrolled technical drawing. "
    "Callouts and arrows annotate key mechanisms.",
    "Classic justice scale with evidence blocks on each side. "
    "One side tips slightly lower.",
    "Dark sea at night. A lighthouse on a rocky cliff. "
    "The beam cuts through mist to reveal a distant shore.",
    "A sturdy bridge spanning a gorge, with a yellow caution sign "
    "and a guardrail. A person pauses to read the sign.",
    "An open door with 'Next Steps' carved into the frame. "
    "A compass on the ground points toward it.",
]


# ── Transport ─────────────────────────────────────────────────────


def run_fixture_transport(prompt_pack: ProviderPromptPack) -> dict:
    """Simulate a local model response from a structured prompt pack.

    Completely offline. Does not:
    - open network connections
    - read environment variables
    - invoke subprocesses
    - call any API

    Produces a dict that validates against ProviderStructuredResponse.

    Args:
        prompt_pack: A built ProviderPromptPack.

    Returns:
        A dict with 'concept_map', 'cards', and 'provider_notes'.
    """
    chunks = prompt_pack.source_chunks
    chunk_ids = sorted(c.chunk_id for c in chunks)
    all_text = " ".join(c.text for c in chunks)
    word_count = len(all_text.split())

    # Build 8 cards with structural variety
    cards: list[dict] = []
    for i in range(8):
        # Distribute source_chunk_ids across cards
        # Card 0-3 use specific chunks; cards 4-7 use larger slices
        if i < 4:
            chunk_idx = min(i, len(chunk_ids) - 1)
            card_sources = [chunk_ids[chunk_idx]]
        elif i < 6:
            card_sources = chunk_ids[: min(3, len(chunk_ids))]
        else:
            card_sources = chunk_ids[:]

        cards.append(
            {
                "title": _CARD_TITLES[i],
                "explanation": _build_explanation(i, chunks, all_text),
                "visual_metaphor": _VISUAL_METAPHORS[i],
                "visual_scene": _VISUAL_SCENES[i],
                "takeaway": _build_takeaway(i, chunks),
                "source_chunk_ids": card_sources,
            }
        )

    return {
        "concept_map": _build_concept_map(chunks),
        "cards": cards,
        "provider_notes": [
            "generated by offline fixture transport",
            "no external API calls were made",
            "no network access",
            "no environment variables read",
            f"processed {len(chunks)} chunks ({word_count} words) into 8 cards",
        ],
    }


# ── Internal builders ─────────────────────────────────────────────


def _build_concept_map(chunks: List) -> dict:
    """Build a concept map response from chunks."""
    all_text = " ".join(c.text for c in chunks)
    sentences = _safe_sentences(all_text)

    # Core problem: use first substantive sentence
    core_problem = sentences[0] if sentences else "Understanding the document content"

    # Extract likely concepts/keywords (simple frequency-based heuristic)
    words = all_text.split()
    key_concepts = _extract_key_phrases(all_text, 5)

    # Key claims: use later sentences that look declarative
    key_claims = [
        s for s in sentences[1:] if len(s) > 30 and not s.startswith("⚠")
    ][:4]
    if not key_claims:
        key_claims = ["The document presents structured information for analysis."]

    return {
        "core_problem": core_problem[:200],
        "key_concepts": key_concepts,
        "key_claims": key_claims,
        "methods_or_mechanisms": _extract_methods(all_text),
        "evidence_or_examples": ["The document contains source material for analysis."],
        "limitations": [
            "This is an offline simulation — not a real language model analysis.",
            "Specific claims should be verified against the original source.",
        ],
        "why_it_matters": (
            "Understanding this material helps build a mental model of the topic. "
            "The content is organized into 8 visual explainer cards for progressive learning."
        ),
    }


def _build_explanation(i: int, chunks, all_text: str) -> str:
    """Build a card explanation that references source chunks."""
    sentences = _safe_sentences(all_text)
    if sentences and i < len(sentences):
        base = sentences[i][:200]
    else:
        base = all_text[:150] if all_text else "Source material"

    explanations = [
        f"This card introduces the main subject. "
        f"The source discusses: {base}",
        f"The core question being addressed relates to the topic. "
        f"Key context: {base}",
        f"The essential insight connects multiple ideas. "
        f"Source excerpt: {base}",
        f"This card explains the mechanism or method. "
        f"Technical description: {base}",
        f"Evidence supporting the claims is examined here. "
        f"Relevant excerpt: {base}",
        f"This material matters because it connects to broader questions. "
        f"Context: {base}",
        f"Every analysis has boundaries. "
        f"This card identifies open questions and caveats. "
        f"Source note: {base}",
        f"The key takeaway for anyone engaging with this topic. "
        f"Final context: {base}",
    ]
    return explanations[i]


def _build_takeaway(i: int, chunks) -> str:
    """Build a concise takeaway for each card."""
    takeaways = [
        "Start with the big picture before diving into details.",
        "Every complex topic has a central question to answer.",
        "The key insight connects ideas you already know to new ones.",
        "Understanding the mechanism makes the result more memorable.",
        "Evidence gives weight to claims — check the sources.",
        "This matters beyond the document — it has real-world relevance.",
        "No analysis is perfect. Knowing the limits is part of understanding.",
        "Now you have a mental map. The next step is yours.",
    ]
    return takeaways[i]


def _extract_key_phrases(text: str, count: int = 5) -> list[str]:
    """Extract plausible key phrases from text (simple heuristic)."""
    words = text.lower().split()
    if not words:
        return ["(no content detected)"]
    # Simple: take longer words that appear in sequence
    candidates = []
    for i in range(len(words) - 1):
        phrase = f"{words[i]} {words[i + 1]}"
        if len(phrase) > 10 and len(phrase) < 60:
            candidates.append(phrase)
    # Return longest unique candidates
    unique = list(dict.fromkeys(candidates))
    unique.sort(key=len, reverse=True)
    return unique[:count] if unique else words[:5]


def _extract_methods(text: str) -> list[str]:
    """Extract plausible method-related sentences."""
    sentences = _safe_sentences(text)
    method_words = [
        "method", "approach", "algorithm", "technique", "process",
        "framework", "model", "architecture", "pipeline", "system",
        "方法", "算法", "架构", "模型", "流程", "技术", "框架",
    ]
    methods = [
        s for s in sentences
        if any(w.lower() in s.lower() for w in method_words)
    ]
    if not methods:
        methods = ["The document describes approaches relevant to its subject matter."]
    return methods[:3]


def _safe_sentences(text: str) -> list[str]:
    """Split text into sentences safely."""
    if not text.strip():
        return []
    raw = text.replace("\n", " ").replace("\r", " ")
    # Simple sentence splitting on . ! ? followed by space or end
    parts = []
    for delim in ["。", ". ", "! ", "? "]:
        if delim in raw:
            parts = raw.split(delim)
            break
    if not parts:
        parts = [raw]
    return [p.strip() for p in parts if p.strip()]
